apiVersion: cache.example.com/v1alpha1
kind: Memcached
metadata:
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: memcached-sample
    app.kubernetes.io/part-of: sample-memcached-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sample-memcached-operator
  name: memcached-sample
spec:
  # TODO(user): Add fields here
  size: 2
  containerPort: 11211
  containerImage: memcached:1.6.24
